import {renderMarkdown} from './markdown';
import type {Store} from '../../shared/contracts/ports';
import {AppError,type DailyReport} from '../../shared/contracts/index';
export function dayAt(time:string,timezone:string){try{return new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(time))}catch{throw new AppError('INVALID_DATE','日期或时区无效。')}}
export function buildReport(store:Store,bookId:string,date:string,timezone:string):DailyReport{
 if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date))||new Date(date).toISOString().slice(0,10)!==date)throw new AppError('INVALID_DATE','日期格式应为有效的 YYYY-MM-DD。');
 dayAt(new Date().toISOString(),timezone);const book=store.get('books',bookId);if(!book)throw new AppError('NOT_FOUND','找不到书籍。',404);
 const onDay=(x:string)=>dayAt(x,timezone)===date;
 const summaries=store.list('summaries',bookId).filter(s=>s.confirmed&&s.confirmedAt&&onDay(s.confirmedAt));
 const saved=store.list('runs',bookId).filter(r=>r.purpose==='daily'&&r.status==='completed').map(r=>({run:r,value:r.result as {advice?:string;date?:string;timezone?:string}|null})).filter(x=>x.value?.date===date&&x.value?.timezone===timezone).sort((a,b)=>b.run.updatedAt.localeCompare(a.run.updatedAt))[0]?.value;
 return {book,date,timezone,activities:store.list('activities',bookId).filter(a=>onDay(a.createdAt)),discussions:store.list('discussions',bookId).filter(d=>onDay(d.createdAt)),summaries,concepts:store.list('concepts',bookId).filter(c=>summaries.some(s=>s.id===c.summaryId)),sources:store.list('sources',bookId),advice:saved?.advice||''};
}
export function escapeHtml(text:unknown){return String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))}
export function renderReport(report:DailyReport){
 const e=escapeHtml;const last=report.activities.at(-1);
 return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'"><title>${e(report.book.title)} · 阅读小结</title><style>body{max-width:860px;margin:60px auto;padding:24px;background:#191919;color:#e6e5e1;font:18px/1.9 Georgia,'Songti SC',serif}h1{font-size:38px}small{color:#aaa}section{border-top:1px solid #444;padding-top:24px;margin-top:32px}p{white-space:pre-wrap;overflow-wrap:anywhere}a{color:#ddd}.md p{white-space:normal}.md h1{font-size:26px}.md h2{font-size:23px}.md h3{font-size:21px}pre,.table-scroll{overflow-x:auto;max-width:100%}pre{padding:16px;background:#242424;font:14px/1.6 monospace}code{overflow-wrap:anywhere}table{border-collapse:collapse;min-width:100%}td,th{border:1px solid #555;padding:8px}blockquote{border-left:2px solid #777;margin-left:0;padding-left:18px}</style></head><body><small>MomentRead · ${e(report.date)} · ${e(report.timezone)}</small><h1>今天，读懂了一点</h1><h2>${e(report.book.title)}</h2><p>${e(report.book.author)}</p><p>${last?`${e(last.chapter)} · 阅读位置 ${(last.progress*100).toFixed(1)}%`:'这一天没有记录阅读位置。'}</p><p>${report.discussions.length} 场讨论 · ${report.concepts.length} 条概念记录 · ${report.summaries.length} 份确认小结</p><section><h2>留下的理解</h2>${report.summaries.length?report.summaries.map(s=>`<article><h3>确认小结 · 版本 ${s.version}</h3><div class="md">${renderMarkdown(s.content)}</div><small>确认于 ${e(s.confirmedAt)} · 讨论 ${e(s.discussionId)}</small></article>`).join(''):'<p>这一天尚无确认小结。</p>'}</section><section><h2>总结与待续问题</h2><div class="md">${renderMarkdown(report.advice||'尚未生成 AI 总结与建议。')}</div></section><section><h2>原文来源</h2>${report.sources.map(s=>`<article><h3>${e(s.title)} · ${e(s.version)}</h3><small>${e(s.language)} · ${e(s.locator)} · ${s.verification==='confirmed'?'已确认对应':'待核对'}</small><p>${e(s.quote)}</p><p>${e(s.url)}</p></article>`).join('')||'<p>尚无可核对的原文来源。</p>'}</section><small>讨论与确认小结不等于已掌握。此文件用于回看，不是完整学习数据备份。</small></body></html>`;
}
